//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cBtn.
        /// </summary>
        internal static string cBtnName {
            get {
                return ResourceManager.GetString("cBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CeBtn.
        /// </summary>
        internal static string CeBtnName {
            get {
                return ResourceManager.GetString("CeBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE.
        /// </summary>
        internal static string clearEntry {
            get {
                return ResourceManager.GetString("clearEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copyItem {
            get {
                return ResourceManager.GetString("copyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string divide {
            get {
                return ResourceManager.GetString("divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotBtn.
        /// </summary>
        internal static string dotBtnName {
            get {
                return ResourceManager.GetString("dotBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string dotName {
            get {
                return ResourceManager.GetString("dotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editItem {
            get {
                return ResourceManager.GetString("editItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eightBtn.
        /// </summary>
        internal static string eightBtnName {
            get {
                return ResourceManager.GetString("eightBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equalBtn.
        /// </summary>
        internal static string equalBtnName {
            get {
                return ResourceManager.GetString("equalBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escapeBtn.
        /// </summary>
        internal static string escapeBtnName {
            get {
                return ResourceManager.GetString("escapeBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string exponentName {
            get {
                return ResourceManager.GetString("exponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileItem {
            get {
                return ResourceManager.GetString("fileItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiveBtn.
        /// </summary>
        internal static string fiveBtnName {
            get {
                return ResourceManager.GetString("fiveBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Sans Serif.
        /// </summary>
        internal static string fontName {
            get {
                return ResourceManager.GetString("fontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourBtn.
        /// </summary>
        internal static string fourBtnName {
            get {
                return ResourceManager.GetString("fourBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputTxtbox.
        /// </summary>
        internal static string inputTxtboxName {
            get {
                return ResourceManager.GetString("inputTxtboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuSettings.
        /// </summary>
        internal static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuStrip.
        /// </summary>
        internal static string menuStripName {
            get {
                return ResourceManager.GetString("menuStripName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string modulus {
            get {
                return ResourceManager.GetString("modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string multiply {
            get {
                return ResourceManager.GetString("multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nineBtn.
        /// </summary>
        internal static string nineBtnName {
            get {
                return ResourceManager.GetString("nineBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add another decimal.
        /// </summary>
        internal static string notDecimal {
            get {
                return ResourceManager.GetString("notDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a decimal to E.
        /// </summary>
        internal static string notExponent {
            get {
                return ResourceManager.GetString("notExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oneBtn.
        /// </summary>
        internal static string oneBtnName {
            get {
                return ResourceManager.GetString("oneBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string pasteItem {
            get {
                return ResourceManager.GetString("pasteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plusBtn.
        /// </summary>
        internal static string plusBtnName {
            get {
                return ResourceManager.GetString("plusBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        internal static string scientificItem {
            get {
                return ResourceManager.GetString("scientificItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sevenBtn.
        /// </summary>
        internal static string sevenBtnName {
            get {
                return ResourceManager.GetString("sevenBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixBtn.
        /// </summary>
        internal static string sixBtnName {
            get {
                return ResourceManager.GetString("sixBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string standardItem {
            get {
                return ResourceManager.GetString("standardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubMenuSettings.
        /// </summary>
        internal static string subMenuSettings {
            get {
                return ResourceManager.GetString("subMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threeBtn.
        /// </summary>
        internal static string threeBtnName {
            get {
                return ResourceManager.GetString("threeBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twoBtn.
        /// </summary>
        internal static string twoBtnName {
            get {
                return ResourceManager.GetString("twoBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zeroBtn.
        /// </summary>
        internal static string zeroBtnName {
            get {
                return ResourceManager.GetString("zeroBtnName", resourceCulture);
            }
        }
    }
}
